name: Cargo test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: |
          cargo test
          # tests without std dont pass for now bcs MemoryStore is used in generative
          # cargo test --no-default-features
          cargo test --all-features
