name: Cargo test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: |
          cargo clippy -- -W clippy::pedantic
          cargo test

          cargo clippy --no-default-features -- -W clippy::pedantic
          # tests without std dont pass for now bcs MemoryStore is used in generative
          # cargo test --no-default-features

          cargo clippy --all-features -- -W clippy::pedantic
          cargo test --all-features

          # I'd run the http example if networking wasn't so unreliable...
          cargo clippy --example http -- -W clippy::pedantic
          cargo clippy --example http-mutithread -- -W clippy::pedantic
